### PR TITLE
Updated the link to the container registry plugin

### PR DESCRIPTION
**Pull request by Ms-Amara**
This added command is helpful as the container-registry plugin installation is required. Added a general link to plugin install.

### CODE REVIEW

**Comment by SueGraham** [comment]
@Ms-Amara Thank you for your suggestions for the Getting Started topic: https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started

The IBM Cloud Container Registry CLI plugin is installed along with the IBM Cloud CLI plugin as part of Step 1. So a separate step to install it is not required.
image

https://cloud.ibm.com/docs/cli?topic=cli-getting-started
image


You are not required to log in to IBM Cloud Container Registry until you want to push your images in step 5. So logging in is not required in step 1.

image

I'll therefore close this issue, but thank you for your feedback.

Regards

Sue Graham

**Comment by SueGraham** [comment]
@Ms-Amara I have just spoken to a member of my team, who confirms that you do now have to install the registry CLI separately - so I'll update the docs - many thanks for your note.

**Comment by SueGraham** [comment]
@Ms-Amara 

I've updated the docs. Thanks for your input.

https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started#gs_registry_cli_install

image

Regards

Sue

**Comment by Ms-Amara** [comment]
Great, thanks Sue!

**Pull request closed without merging**
